In [5]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go
import pandas as pd
import psycopg2 as pg

In [6]:
from sqlalchemy import create_engine

In [7]:
import os
from pathlib import Path

In [25]:
###########  Define PostgreSQL connection
conn = pg.connect(
    database="airbus",
    user="tableau",
    password="d3f@ulT_9G_p@ss",
    host="dbgw.publicrelay.com",
    port="5432")

In [26]:
df = pd.read_sql_query(
    f"""
    SELECT article_id, outlet_name, tag_name, provider, provider_value, zip_code
    FROM bhqlite
    WHERE intake_date >= '12/31/2015'
    AND intake_date <= '1/1/2017'
    """,
    con=conn)

In [27]:
df

,article_id,outlet_name,tag_name,provider,provider_value,zip_code
0,2204316724,Air Transport World,Airbus:Aircraft Production,GnipTwitter,14.0,20910
1,2204316724,Air Transport World,A350,GnipTwitter,14.0,20910
2,2204316724,Air Transport World,Aircraft Production,GnipTwitter,14.0,20910
3,2204316724,Air Transport World,Airbus,GnipTwitter,14.0,20910
4,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018
5,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018
6,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018
7,2203628156,New York Times,Airbus,Majestic,299.0,10018
8,2203628156,New York Times,Airbus,Majestic,299.0,10018
9,2203628156,New York Times,Airbus,Majestic,299.0,10018
10,2203628156,New York Times,Boeing,Majestic,299.0,10018
11,2203628156,New York Times,Boeing,Majestic,299.0,10018
12,2203628156,New York Times,Boeing,Majestic,299.0,10018
13,2203377430,CNN,737,GnipTwitter,7.0,30303
14,2203377430,CNN,A350,GnipTwitter,7.0,30303
15,2203377430,CNN,Airbus,GnipTwitter,7.0,30303
16,2203377430,CNN,A330,GnipTwitter,7.0,30303
17,2203377430,CNN,Asia-Pacific,GnipTwitter,7.0,30303
18,2203377430,CNN,Boeing,GnipTwitter,7.0,30303
19,2203377430,CNN,A321NEO,GnipTwitter,7.0,30303
20,2203377430,CNN,787,GnipTwitter,7.0,30303
21,2203377430,CNN,777,GnipTwitter,7.0,30303
22,2203401776,CNN Money,737,GnipTwitter,7.0,10019
23,2203401776,CNN Money,A350,GnipTwitter,7.0,10019
24,2203401776,CNN Money,Airbus,GnipTwitter,7.0,10019
25,2203401776,CNN Money,A330,GnipTwitter,7.0,10019
26,2203401776,CNN Money,Asia-Pacific,GnipTwitter,7.0,10019
27,2203401776,CNN Money,Boeing,GnipTwitter,7.0,10019
28,2203401776,CNN Money,A321NEO,GnipTwitter,7.0,10019
29,2203401776,CNN Money,787,GnipTwitter,7.0,10019
...,...,...,...,...,...,...
38590,2201899183,@NewYorkCP,Airbus,None,NaN,13425
38591,2201899183,@NewYorkCP,A321,None,NaN,13425
38592,2367597833,Victor Harbor Times,Fuel Efficiency,None,NaN,5211
38593,2367597833,Victor Harbor Times,A350,None,NaN,5211
38594,2367597833,Victor Harbor Times,Cabin Technology,None,NaN,5211
38595,2367597833,Victor Harbor Times,A330,None,NaN,5211
38596,2367597833,Victor Harbor Times,Airbus:Cabin Technology,None,NaN,5211
38597,2367597833,Victor Harbor Times,Boeing,None,NaN,5211
38598,2367597833,Victor Harbor Times,Technology,None,NaN,5211
38599,2367597833,Victor Harbor Times,A320,None,NaN,5211
38600,2367597833,Victor Harbor Times,Airbus:Fuel Efficiency,None,NaN,5211
38601,2367597833,Victor Harbor Times,Airbus,None,NaN,5211
38602,2367597833,Victor Harbor Times,787,None,NaN,5211
38603,2367597833,Victor Harbor Times,A380,None,NaN,5211
38604,2367597833,Victor Harbor Times,Airbus:Technology,None,NaN,5211
38605,2298705886,Sydney Morning Herald,Safety,None,NaN,NSW 2001
38606,2298705886,Sydney Morning Herald,Airbus,None,NaN,NSW 2001
38607,2298705886,Sydney Morning Herald,A321,None,NaN,NSW 2001
38608,2199743813,Binghamton Homepage,757,None,NaN,13903
38609,2199743813,Binghamton Homepage,Boeing,None,NaN,13903
38610,2380343416,@planet4589,Corporate,None,NaN,02143
38611,2380343416,@planet4589,Airbus,None,NaN,02143
38612,2380343416,@planet4589,Airbus:Corporate,None,NaN,02143
38613,2355426359,The Guardian,A350 XWB,None,NaN,N19GU
38614,2355426359,The Guardian,787-9,None,NaN,N19GU
38615,2355426359,The Guardian,A350,None,NaN,N19GU
38616,2355426359,The Guardian,Boeing,None,NaN,N19GU
38617,2355426359,The Guardian,Airbus,None,NaN,N19GU
38618,2355426359,The Guardian,A380,None,NaN,N19GU
38619,2355426359,The Guardian,787,None,NaN,N19GU

In [28]:
###### Define engine with sqlalchemy
def getEngine(DB_HOST, DB_PORT, DB_SCHEMA, DB_USER, DB_PASS):
    db_string = ("postgres://%s:%s@%s:%d/%s"%(DB_USER,DB_PASS,DB_HOST,DB_PORT,DB_SCHEMA));
    global engine
    engine = create_engine(db_string, echo=False)

In [29]:
getEngine(DB_HOST='localhost', DB_PORT=5432, DB_SCHEMA='postgres', DB_USER='postgres', DB_PASS='pg_p@ss')

In [30]:
df.to_sql('airbus_bhqlite_excerpt', con=engine, if_exists='replace')

## Begin actual script

In [31]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go
import pandas as pd
import psycopg2 as pg
import os
from pathlib import Path

In [32]:
###########  Define PostgreSQL connection
conn = pg.connect(
    database="postgres",
    user="postgres",
    password="pg_p@ss",
    host="localhost",
    port="5432")

In [44]:
df = pd.read_sql_query(
    f"""
    SELECT article_id, outlet_name, tag_name, provider, provider_value, zip_code
    FROM airbus_bhqlite_excerpt
    """,
    con=conn)

In [45]:
df.head()

,article_id,outlet_name,tag_name,provider,provider_value,zip_code
0,2204316724,Air Transport World,Airbus:Aircraft Production,GnipTwitter,14.0,20910
1,2204316724,Air Transport World,A350,GnipTwitter,14.0,20910
2,2204316724,Air Transport World,Aircraft Production,GnipTwitter,14.0,20910
3,2204316724,Air Transport World,Airbus,GnipTwitter,14.0,20910
4,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018

In [46]:
df['parent_tag'] = df['tag_name'].str.split(':').str.get(0)

In [47]:
df['child_tag'] = df['tag_name'].str.split(':').str.get(1)

In [48]:
df

,article_id,outlet_name,tag_name,provider,provider_value,zip_code,parent_tag,child_tag
0,2204316724,Air Transport World,Airbus:Aircraft Production,GnipTwitter,14.0,20910,Airbus,Aircraft Production
1,2204316724,Air Transport World,A350,GnipTwitter,14.0,20910,A350,NaN
2,2204316724,Air Transport World,Aircraft Production,GnipTwitter,14.0,20910,Aircraft Production,NaN
3,2204316724,Air Transport World,Airbus,GnipTwitter,14.0,20910,Airbus,NaN
4,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,Fuel Efficiency,NaN
5,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,Fuel Efficiency,NaN
6,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,Fuel Efficiency,NaN
7,2203628156,New York Times,Airbus,Majestic,299.0,10018,Airbus,NaN
8,2203628156,New York Times,Airbus,Majestic,299.0,10018,Airbus,NaN
9,2203628156,New York Times,Airbus,Majestic,299.0,10018,Airbus,NaN
10,2203628156,New York Times,Boeing,Majestic,299.0,10018,Boeing,NaN
11,2203628156,New York Times,Boeing,Majestic,299.0,10018,Boeing,NaN
12,2203628156,New York Times,Boeing,Majestic,299.0,10018,Boeing,NaN
13,2203377430,CNN,737,GnipTwitter,7.0,30303,737,NaN
14,2203377430,CNN,A350,GnipTwitter,7.0,30303,A350,NaN
15,2203377430,CNN,Airbus,GnipTwitter,7.0,30303,Airbus,NaN
16,2203377430,CNN,A330,GnipTwitter,7.0,30303,A330,NaN
17,2203377430,CNN,Asia-Pacific,GnipTwitter,7.0,30303,Asia-Pacific,NaN
18,2203377430,CNN,Boeing,GnipTwitter,7.0,30303,Boeing,NaN
19,2203377430,CNN,A321NEO,GnipTwitter,7.0,30303,A321NEO,NaN
20,2203377430,CNN,787,GnipTwitter,7.0,30303,787,NaN
21,2203377430,CNN,777,GnipTwitter,7.0,30303,777,NaN
22,2203401776,CNN Money,737,GnipTwitter,7.0,10019,737,NaN
23,2203401776,CNN Money,A350,GnipTwitter,7.0,10019,A350,NaN
24,2203401776,CNN Money,Airbus,GnipTwitter,7.0,10019,Airbus,NaN
25,2203401776,CNN Money,A330,GnipTwitter,7.0,10019,A330,NaN
26,2203401776,CNN Money,Asia-Pacific,GnipTwitter,7.0,10019,Asia-Pacific,NaN
27,2203401776,CNN Money,Boeing,GnipTwitter,7.0,10019,Boeing,NaN
28,2203401776,CNN Money,A321NEO,GnipTwitter,7.0,10019,A321NEO,NaN
29,2203401776,CNN Money,787,GnipTwitter,7.0,10019,787,NaN
...,...,...,...,...,...,...,...,...
38590,2201899183,@NewYorkCP,Airbus,None,NaN,13425,Airbus,NaN
38591,2201899183,@NewYorkCP,A321,None,NaN,13425,A321,NaN
38592,2367597833,Victor Harbor Times,Fuel Efficiency,None,NaN,5211,Fuel Efficiency,NaN
38593,2367597833,Victor Harbor Times,A350,None,NaN,5211,A350,NaN
38594,2367597833,Victor Harbor Times,Cabin Technology,None,NaN,5211,Cabin Technology,NaN
38595,2367597833,Victor Harbor Times,A330,None,NaN,5211,A330,NaN
38596,2367597833,Victor Harbor Times,Airbus:Cabin Technology,None,NaN,5211,Airbus,Cabin Technology
38597,2367597833,Victor Harbor Times,Boeing,None,NaN,5211,Boeing,NaN
38598,2367597833,Victor Harbor Times,Technology,None,NaN,5211,Technology,NaN
38599,2367597833,Victor Harbor Times,A320,None,NaN,5211,A320,NaN
38600,2367597833,Victor Harbor Times,Airbus:Fuel Efficiency,None,NaN,5211,Airbus,Fuel Efficiency
38601,2367597833,Victor Harbor Times,Airbus,None,NaN,5211,Airbus,NaN
38602,2367597833,Victor Harbor Times,787,None,NaN,5211,787,NaN
38603,2367597833,Victor Harbor Times,A380,None,NaN,5211,A380,NaN
38604,2367597833,Victor Harbor Times,Airbus:Technology,None,NaN,5211,Airbus,Technology
38605,2298705886,Sydney Morning Herald,Safety,None,NaN,NSW 2001,Safety,NaN
38606,2298705886,Sydney Morning Herald,Airbus,None,NaN,NSW 2001,Airbus,NaN
38607,2298705886,Sydney Morning Herald,A321,None,NaN,NSW 2001,A321,NaN
38608,2199743813,Binghamton Homepage,757,None,NaN,13903,757,NaN
38609,2199743813,Binghamton Homepage,Boeing,None,NaN,13903,Boeing,NaN
38610,2380343416,@planet4589,Corporate,None,NaN,02143,Corporate,NaN
38611,2380343416,@planet4589,Airbus,None,NaN,02143,Airbus,NaN
38612,2380343416,@planet4589,Airbus:Corporate,None,NaN,02143,Airbus,Corporate
38613,2355426359,The Guardian,A350 XWB,None,NaN,N19GU,A350 XWB,NaN
38614,2355426359,The Guardian,787-9,None,NaN,N19GU,787-9,NaN
38615,2355426359,The Guardian,A350,None,NaN,N19GU,A350,NaN
38616,2355426359,The Guardian,Boeing,None,NaN,N19GU,Boeing,NaN
38617,2355426359,The Guardian,Airbus,None,NaN,N19GU,Airbus,NaN
38618,2355426359,The Guardian,A380,None,NaN,N19GU,A380,NaN
38619,2355426359,The Guardian,787,None,NaN,N19GU,787,NaN

In [49]:
indexNames = df[(df['provider'] == 'Majestic') | (df['provider'] == 'GnipTwitter:Retro') | (df['provider'] == 'LinkedIn') | (df['provider'] == 'Facebook:comments')].index
df.drop(indexNames, inplace=True)

In [50]:
df['provider'].value_counts()

GnipTwitter        6356
Facebook:shares    3143
Name: provider, dtype: int64

In [51]:
df['child_tag'].value_counts()

Financial Perf.         989
Aircraft Production     836
Sales                   765
Corporate               439
Airbus                  438
Boeing                  333
Fuel Efficiency         323
Technology              319
Spokesperson            249
Cabin Technology        221
Government Relations    166
Asia-Pacific            143
Share Value             124
Earnings                103
CEO                      98
Influencer Feedback      88
Middle East              76
Labor Relations          66
Bombardier               63
M&A                      51
Safety                   48
Legislation              41
United States            38
North America            30
Eurozone                 30
United Kingdom           25
EU ETS                   19
Passenger Safety         19
Emerging Technology      17
Employee                 14
FAA                      12
Tech Safety               8
CSR                       4
Fuel Prices               3
Winglets/Sharklets        3
Litigation                2
Customer Service          2
India                     1
Financial Analyst         1
Noise Reduction           1
Latin America             1
Name: child_tag, dtype: int64

In [52]:
parent_tag_list = ['Airbus', 'Boeing']
child_tag_list = ['Aircraft Production', 'Corporate', 'Financial Perf.', 'Safety', 'Government Relations', 'Technology']

In [53]:
df_filtered = df[df['tag_name'] == 'Airbus:Corporate']

In [54]:
df_filtered

,article_id,outlet_name,tag_name,provider,provider_value,zip_code,parent_tag,child_tag
3400,2247525465,iTnews Australia,Airbus:Corporate,GnipTwitter,6.0,2016,Airbus,Corporate
5243,2395661284,South China Morning Post,Airbus:Corporate,GnipTwitter,43.0,00000,Airbus,Corporate
5263,2395661284,South China Morning Post,Airbus:Corporate,Facebook:shares,11.0,00000,Airbus,Corporate
5578,2396806814,Hindu Business Line,Airbus:Corporate,Facebook:shares,1.0,600002,Airbus,Corporate
6052,2321454507,Bloomberg,Airbus:Corporate,GnipTwitter,10.0,10022,Airbus,Corporate
6180,2322211302,Wall Street Journal,Airbus:Corporate,Facebook:shares,2.0,10281,Airbus,Corporate
6181,2322211302,Wall Street Journal,Airbus:Corporate,Facebook:shares,2.0,10281,Airbus,Corporate
6182,2322211302,Wall Street Journal,Airbus:Corporate,Facebook:shares,2.0,10281,Airbus,Corporate
6201,2322211302,Wall Street Journal,Airbus:Corporate,GnipTwitter,4.0,10281,Airbus,Corporate
6202,2322211302,Wall Street Journal,Airbus:Corporate,GnipTwitter,4.0,10281,Airbus,Corporate
6203,2322211302,Wall Street Journal,Airbus:Corporate,GnipTwitter,4.0,10281,Airbus,Corporate
7289,2334390647,Sky News,Airbus:Corporate,GnipTwitter,338.0,TW7 5QD,Airbus,Corporate
7299,2334589240,Yahoo! Finance UK,Airbus:Corporate,GnipTwitter,2.0,WC2H 8AD,Airbus,Corporate
7307,2334318680,The Telegraph (UK),Airbus:Corporate,GnipTwitter,1.0,ME4 4TT,Airbus,Corporate
7316,2334233940,Bloomberg,Airbus:Corporate,GnipTwitter,5.0,10022,Airbus,Corporate
7603,2335164149,New York Times,Airbus:Corporate,GnipTwitter,2.0,10018,Airbus,Corporate
7604,2335164149,New York Times,Airbus:Corporate,GnipTwitter,2.0,10018,Airbus,Corporate
7605,2335164149,New York Times,Airbus:Corporate,GnipTwitter,2.0,10018,Airbus,Corporate
7929,2343770147,The Telegraph (UK),Airbus:Corporate,GnipTwitter,2.0,ME4 4TT,Airbus,Corporate
8341,2350134776,Economic Times,Airbus:Corporate,GnipTwitter,12.0,110002,Airbus,Corporate
8365,2350113080,Yahoo! Finance UK,Airbus:Corporate,GnipTwitter,1.0,WC2H 8AD,Airbus,Corporate
8389,2350106127,Yahoo! News,Airbus:Corporate,GnipTwitter,1.0,94089,Airbus,Corporate
8413,2350102805,Yahoo! Finance,Airbus:Corporate,GnipTwitter,1.0,00000,Airbus,Corporate
8893,2357157359,Seattle Times,Airbus:Corporate,GnipTwitter,22.0,98109,Airbus,Corporate
8894,2357157359,Seattle Times,Airbus:Corporate,GnipTwitter,22.0,98109,Airbus,Corporate
8895,2357157359,Seattle Times,Airbus:Corporate,GnipTwitter,22.0,98109,Airbus,Corporate
9177,2360249604,Business Insider,Airbus:Corporate,GnipTwitter,1.0,10010,Airbus,Corporate
9201,2360249604,Business Insider,Airbus:Corporate,Facebook:shares,1.0,10010,Airbus,Corporate
9213,2359576304,Reuters,Airbus:Corporate,Facebook:shares,150.0,10036,Airbus,Corporate
9225,2359576304,Reuters,Airbus:Corporate,GnipTwitter,119.0,10036,Airbus,Corporate
...,...,...,...,...,...,...,...,...
34050,2359567530,Metro.us,Airbus:Corporate,None,NaN,19102,Airbus,Corporate
35007,2350122198,Channel NewsAsia,Airbus:Corporate,None,NaN,299939,Airbus,Corporate
35060,2350109961,Reuters UK,Airbus:Corporate,None,NaN,E14 5EP,Airbus,Corporate
35360,2335193742,The Telegraph (UK),Airbus:Corporate,None,NaN,ME4 4TT,Airbus,Corporate
35394,2398860932,@nicx62,Airbus:Corporate,None,NaN,None,Airbus,Corporate
35735,2334392019,Heart Radio,Airbus:Corporate,None,NaN,00000,Airbus,Corporate
36239,2370964167,International Business Times India,Airbus:Corporate,None,NaN,560008,Airbus,Corporate
36299,2392575805,Agence France-Presse,Airbus:Corporate,None,NaN,75002,Airbus,Corporate
36310,2350103171,Sharenet,Airbus:Corporate,None,NaN,7966,Airbus,Corporate
36375,2334432767,SamFM.co.uk,Airbus:Corporate,None,NaN,BS3 2JH,Airbus,Corporate
36544,2350109960,Yahoo! Finance UK,Airbus:Corporate,None,NaN,WC2H 8AD,Airbus,Corporate
36705,2326881312,@R_Wall,Airbus:Corporate,None,NaN,None,Airbus,Corporate
36752,2414066226,Force India,Airbus:Corporate,None,NaN,None,Airbus,Corporate
36882,2397633136,@5amStartups,Airbus:Corporate,None,NaN,None,Airbus,Corporate
36914,2359564872,Yahoo! Finance,Airbus:Corporate,None,NaN,00000,Airbus,Corporate
36925,2379321267,Yahoo! India,Airbus:Corporate,None,NaN,00000,Airbus,Corporate
36998,2379316457,Yahoo! News Singapore,Airbus:Corporate,None,NaN,None,Airbus,Corporate
37465,2359660533,Yahoo! News Singapore,Airbus:Corporate,None,NaN,None,Airbus,Corporate
37574,2350108418,92.9 WLMI,Airbus:Corporate,None,NaN,48842,Airbus,Corporate
37671,2379321266,Philadelphia Inquirer,Airbus:Corporate,None,NaN,19101,Airbus,Corporate
37672,2379321266,Philadelphia Inquirer,Airbus:Corporate,None,NaN,19101,Airbus,Corporate
37673,2379321266,Philadelphia Inquirer,Airbus:Corporate,None,NaN,19101,Airbus,Corporate
37790,2359665783,Edge Markets,Airbus:Corporate,None,NaN,00000,Airbus,Corporate
37930,2359564450,WTAQ News Talk,Airbus:Corporate,None,NaN,54305,Airbus,Corporate
38104,2334440170,Metro Radio,Airbus:Corporate,None,NaN,NE1 6BL,Airbus,Corporate
38146,2334392912,Lakeland Radio,Airbus:Corporate,None,NaN,LA8 8QJ,Airbus,Corporate
38274,2350174182,Metro.us,Airbus:Corporate,None,NaN,19102,Airbus,Corporate
38456,2334399270,Radio City Talk,Airbus:Corporate,None,NaN,L1 1RL,Airbus,Corporate
38461,2379310198,Sharenet,Airbus:Corporate,None,NaN,7966,Airbus,Corporate
38612,2380343416,@planet4589,Airbus:Corporate,None,NaN,02143,Airbus,Corporate

In [73]:
df_outlet_volume = df.groupby('outlet_name')[['article_id']].nunique().reset_index()

In [69]:
df_outlet_sharing = df.groupby(['outlet_name', 'article_id', 'provider'])[['provider_value']].min().reset_index()

In [71]:
df_outlet_sharing_totals = df_outlet_sharing.groupby('outlet_name')[['provider_value']].sum().reset_index()

In [72]:
df_outlet_sharing_totals

                                    outlet_name  provider_value
0                                      11 Alive             1.0
1                                   3DPrint.com           137.0
2                                     4 Traders             1.0
3                                      680 News             3.0
4                                      ABC News           157.0
5                                       AIRwise             1.0
6                                      AME Info            18.0
7                               AVIATIONNEWS.EU             2.0
8                              Accounting Today            19.0
9                             Ace News Services             1.0
10                         Aerospace Technology            32.0
11                 Aerospace Technology-Updates            28.0
12                         Agence France-Presse           516.0
13                      Agence Kampuchea Presse            11.0
14                              Air Cargo World             7.0
15                          Air Transport World           411.0
16                                     Airchive            15.0
17                                 Airways News            15.0
18                                     Al Ahram             5.0
19                                   Al Jazeera            63.0
20                           Albury Border Mail             5.0
21                                   All Africa            27.0
22                                       Aloria           917.0
23   American Journal of Transportation On-Line             8.0
24                           American Machinist             2.0
25                                     An Nahar             1.0
26                         Anchorage Daily News           108.0
27                                    Anna.aero            15.0
28                                    Arab News             1.0
29                            Arabian Aerospace            12.0
..                                          ...             ...
328                                WBAL Channel            14.0
329                                  WBOC TV 16             1.0
330                                        WHBL             1.0
331                                        WHTC             1.0
332                                        WKRG          1198.0
333                                        WLTX             1.0
334                                        WRAL             1.0
335                                        WTHR             3.0
336                                Wales Online             1.0
337                         Wall Street Journal          7113.0
338                             Washington Post           609.0
339                            Wauchope Gazette             1.0
340                             West Australian             6.0
341                    Wichita Business Journal             1.0
342                               Wichita Eagle           238.0
343                          Xinhua News Agency            87.0
344                              Yahoo! Finance            73.0
345                           Yahoo! Finance UK            55.0
346                                Yahoo! India            34.0
347                                 Yahoo! News           228.0
348                       Yahoo! News Australia             3.0
349                          Yahoo! News Canada             3.0
350                       Yahoo! News Singapore             1.0
351                          Yeshiva World News             4.0
352                Young Travelers of Hong Kong             2.0
353                                       ZDNet           187.0
354                              bivnze's space             3.0
355                             defencetalk.com             1.0
356                                    gCaptain           102.0
357                            iTnews Australia             7.0

[358 rows x 2 columns]

In [74]:
df_outlet_merged = pd.merge(df_outlet_volume, df_outlet_sharing_totals, how='left', on='outlet_name')

In [76]:
df_outlet_merged = df_outlet_merged.fillna(0)

In [77]:
df_outlet_merged

,outlet_name,article_id,provider_value
0,#GCC and #MiddleEast Finance News,1,0.0
1,100 WAPI,1,0.0
2,1057 EZRrock,1,0.0
3,11 Alive,1,1.0
4,12 News Now,1,0.0
5,14 WFIE,2,0.0
6,1440 WNFL,11,0.0
7,1490Wosh.com,1,0.0
8,16 WAPT,2,0.0
9,19 Action News,1,0.0
10,3 WRCB-TV,1,0.0
11,35 WSEE,1,0.0
12,3DPrint.com,1,137.0
13,3FM,1,0.0
14,3novicesafrican,2,0.0
15,3novicesasia,4,0.0
16,4 Traders,49,1.0
17,4029 TV,1,0.0
18,41 NBC,1,0.0
19,570 News,2,0.0
20,580 CFRA,1,0.0
21,590 KLBJ,1,0.0
22,660 News,2,0.0
23,680 News,2,3.0
24,77 WABC RADIO,1,0.0
25,92.9 WLMI,32,0.0
26,94.5 KSMB,1,0.0
27,949 KCMO,1,0.0
28,96.4 Eagle Radio,1,0.0
29,997WTN.com,1,0.0
...,...,...,...
1539,XinMsn,2,0.0
1540,Xinhua News Agency,9,87.0
1541,YOUR BASIN,2,0.0
1542,Yahoo! Finance,61,73.0
1543,Yahoo! Finance UK,78,55.0
1544,Yahoo! India,33,34.0
1545,Yahoo! Maktoob News,10,0.0
1546,Yahoo! New Zealand News,9,0.0
1547,Yahoo! News,33,228.0
1548,Yahoo! News Australia,10,3.0
1549,Yahoo! News Canada,25,3.0
1550,Yahoo! News Singapore,39,1.0
1551,Yakima Herald,1,0.0
1552,Yass Tribune,4,0.0
1553,Yerepouni Daily News.,1,0.0
1554,Yeshiva World News,1,4.0
1555,Young Travelers of Hong Kong,1,2.0
1556,YourCentralValley.com,1,0.0
1557,ZDNet,1,187.0
1558,ZeeNews.com,2,0.0
1559,Zionsville Times Sentinel,1,0.0
1560,bivnze's space,1,3.0
1561,defencetalk.com,1,1.0
1562,gCaptain,1,102.0
1563,iTnews Australia,3,7.0
1564,news and real estate,1,0.0
1565,rci-ventures,1,0.0
1566,satPRnews,4,0.0
1567,αακηρατος δελφων,1,0.0
1568,بلیط یاب - راهنمای خرید بلیط هواپیمابلیط یاب –...,9,0.0