In [1]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go
import pandas as pd
import psycopg2 as pg

In [2]:
from sqlalchemy import create_engine

In [3]:
import os
from pathlib import Path

In [4]:
###########  Define PostgreSQL connection
conn = pg.connect(
    database="airbus",
    user="tableau",
    password="d3f@ulT_9G_p@ss",
    host="dbgw.publicrelay.com",
    port="5432")

In [5]:
df = pd.read_sql_query(
    f"""
    SELECT article_id, outlet_name, tag_name, provider, provider_value, zip_code, reach_circulation
    FROM bhqlite
    WHERE intake_date >= '12/31/2015'
    AND intake_date <= '1/1/2017'
    """,
    con=conn)

In [6]:
df

,article_id,outlet_name,tag_name,provider,provider_value,zip_code,reach_circulation
0,2204316724,Air Transport World,Airbus:Aircraft Production,GnipTwitter,14.0,20910,154308
1,2204316724,Air Transport World,A350,GnipTwitter,14.0,20910,154308
2,2204316724,Air Transport World,Aircraft Production,GnipTwitter,14.0,20910,154308
3,2204316724,Air Transport World,Airbus,GnipTwitter,14.0,20910,154308
4,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,76865318
5,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,76865318
6,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,76865318
7,2203628156,New York Times,Airbus,Majestic,299.0,10018,76865318
8,2203628156,New York Times,Airbus,Majestic,299.0,10018,76865318
9,2203628156,New York Times,Airbus,Majestic,299.0,10018,76865318
10,2203628156,New York Times,Boeing,Majestic,299.0,10018,76865318
11,2203628156,New York Times,Boeing,Majestic,299.0,10018,76865318
12,2203628156,New York Times,Boeing,Majestic,299.0,10018,76865318
13,2203377430,CNN,737,GnipTwitter,7.0,30303,76918430
14,2203377430,CNN,A350,GnipTwitter,7.0,30303,76918430
15,2203377430,CNN,Airbus,GnipTwitter,7.0,30303,76918430
16,2203377430,CNN,A330,GnipTwitter,7.0,30303,76918430
17,2203377430,CNN,Asia-Pacific,GnipTwitter,7.0,30303,76918430
18,2203377430,CNN,Boeing,GnipTwitter,7.0,30303,76918430
19,2203377430,CNN,A321NEO,GnipTwitter,7.0,30303,76918430
20,2203377430,CNN,787,GnipTwitter,7.0,30303,76918430
21,2203377430,CNN,777,GnipTwitter,7.0,30303,76918430
22,2203401776,CNN Money,737,GnipTwitter,7.0,10019,11800000
23,2203401776,CNN Money,A350,GnipTwitter,7.0,10019,11800000
24,2203401776,CNN Money,Airbus,GnipTwitter,7.0,10019,11800000
25,2203401776,CNN Money,A330,GnipTwitter,7.0,10019,11800000
26,2203401776,CNN Money,Asia-Pacific,GnipTwitter,7.0,10019,11800000
27,2203401776,CNN Money,Boeing,GnipTwitter,7.0,10019,11800000
28,2203401776,CNN Money,A321NEO,GnipTwitter,7.0,10019,11800000
29,2203401776,CNN Money,787,GnipTwitter,7.0,10019,11800000
...,...,...,...,...,...,...,...
38590,2201899183,@NewYorkCP,Airbus,None,NaN,13425,6446
38591,2201899183,@NewYorkCP,A321,None,NaN,13425,6446
38592,2367597833,Victor Harbor Times,Fuel Efficiency,None,NaN,5211,2038
38593,2367597833,Victor Harbor Times,A350,None,NaN,5211,2038
38594,2367597833,Victor Harbor Times,Cabin Technology,None,NaN,5211,2038
38595,2367597833,Victor Harbor Times,A330,None,NaN,5211,2038
38596,2367597833,Victor Harbor Times,Airbus:Cabin Technology,None,NaN,5211,2038
38597,2367597833,Victor Harbor Times,Boeing,None,NaN,5211,2038
38598,2367597833,Victor Harbor Times,Technology,None,NaN,5211,2038
38599,2367597833,Victor Harbor Times,A320,None,NaN,5211,2038
38600,2367597833,Victor Harbor Times,Airbus:Fuel Efficiency,None,NaN,5211,2038
38601,2367597833,Victor Harbor Times,Airbus,None,NaN,5211,2038
38602,2367597833,Victor Harbor Times,787,None,NaN,5211,2038
38603,2367597833,Victor Harbor Times,A380,None,NaN,5211,2038
38604,2367597833,Victor Harbor Times,Airbus:Technology,None,NaN,5211,2038
38605,2298705886,Sydney Morning Herald,Safety,None,NaN,NSW 2001,3461674
38606,2298705886,Sydney Morning Herald,Airbus,None,NaN,NSW 2001,3461674
38607,2298705886,Sydney Morning Herald,A321,None,NaN,NSW 2001,3461674
38608,2199743813,Binghamton Homepage,757,None,NaN,13903,18349
38609,2199743813,Binghamton Homepage,Boeing,None,NaN,13903,18349
38610,2380343416,@planet4589,Corporate,None,NaN,02143,23350
38611,2380343416,@planet4589,Airbus,None,NaN,02143,23350
38612,2380343416,@planet4589,Airbus:Corporate,None,NaN,02143,23350
38613,2355426359,The Guardian,A350 XWB,None,NaN,N19GU,225629
38614,2355426359,The Guardian,787-9,None,NaN,N19GU,225629
38615,2355426359,The Guardian,A350,None,NaN,N19GU,225629
38616,2355426359,The Guardian,Boeing,None,NaN,N19GU,225629
38617,2355426359,The Guardian,Airbus,None,NaN,N19GU,225629
38618,2355426359,The Guardian,A380,None,NaN,N19GU,225629
38619,2355426359,The Guardian,787,None,NaN,N19GU,225629

In [7]:
###### Define engine with sqlalchemy
def getEngine(DB_HOST, DB_PORT, DB_SCHEMA, DB_USER, DB_PASS):
    db_string = ("postgres://%s:%s@%s:%d/%s"%(DB_USER,DB_PASS,DB_HOST,DB_PORT,DB_SCHEMA));
    global engine
    engine = create_engine(db_string, echo=False)

In [8]:
getEngine(DB_HOST='localhost', DB_PORT=5432, DB_SCHEMA='postgres', DB_USER='postgres', DB_PASS='pg_p@ss')

In [9]:
df.to_sql('airbus_bhqlite_excerpt', con=engine, if_exists='replace')

## Begin actual script

In [10]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go
import pandas as pd
import psycopg2 as pg
import os
from pathlib import Path

In [11]:
###########  Define PostgreSQL connection
conn = pg.connect(
    database="postgres",
    user="postgres",
    password="pg_p@ss",
    host="localhost",
    port="5432")

In [12]:
df = pd.read_sql_query(
    f"""
    SELECT article_id, outlet_name, tag_name, provider, provider_value, zip_code, reach_circulation
    FROM airbus_bhqlite_excerpt
    """,
    con=conn)

In [13]:
df

,article_id,outlet_name,tag_name,provider,provider_value,zip_code,reach_circulation
0,2204316724,Air Transport World,Airbus:Aircraft Production,GnipTwitter,14.0,20910,154308
1,2204316724,Air Transport World,A350,GnipTwitter,14.0,20910,154308
2,2204316724,Air Transport World,Aircraft Production,GnipTwitter,14.0,20910,154308
3,2204316724,Air Transport World,Airbus,GnipTwitter,14.0,20910,154308
4,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,76865318
5,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,76865318
6,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,76865318
7,2203628156,New York Times,Airbus,Majestic,299.0,10018,76865318
8,2203628156,New York Times,Airbus,Majestic,299.0,10018,76865318
9,2203628156,New York Times,Airbus,Majestic,299.0,10018,76865318
10,2203628156,New York Times,Boeing,Majestic,299.0,10018,76865318
11,2203628156,New York Times,Boeing,Majestic,299.0,10018,76865318
12,2203628156,New York Times,Boeing,Majestic,299.0,10018,76865318
13,2203377430,CNN,737,GnipTwitter,7.0,30303,76918430
14,2203377430,CNN,A350,GnipTwitter,7.0,30303,76918430
15,2203377430,CNN,Airbus,GnipTwitter,7.0,30303,76918430
16,2203377430,CNN,A330,GnipTwitter,7.0,30303,76918430
17,2203377430,CNN,Asia-Pacific,GnipTwitter,7.0,30303,76918430
18,2203377430,CNN,Boeing,GnipTwitter,7.0,30303,76918430
19,2203377430,CNN,A321NEO,GnipTwitter,7.0,30303,76918430
20,2203377430,CNN,787,GnipTwitter,7.0,30303,76918430
21,2203377430,CNN,777,GnipTwitter,7.0,30303,76918430
22,2203401776,CNN Money,737,GnipTwitter,7.0,10019,11800000
23,2203401776,CNN Money,A350,GnipTwitter,7.0,10019,11800000
24,2203401776,CNN Money,Airbus,GnipTwitter,7.0,10019,11800000
25,2203401776,CNN Money,A330,GnipTwitter,7.0,10019,11800000
26,2203401776,CNN Money,Asia-Pacific,GnipTwitter,7.0,10019,11800000
27,2203401776,CNN Money,Boeing,GnipTwitter,7.0,10019,11800000
28,2203401776,CNN Money,A321NEO,GnipTwitter,7.0,10019,11800000
29,2203401776,CNN Money,787,GnipTwitter,7.0,10019,11800000
...,...,...,...,...,...,...,...
38590,2201899183,@NewYorkCP,Airbus,None,NaN,13425,6446
38591,2201899183,@NewYorkCP,A321,None,NaN,13425,6446
38592,2367597833,Victor Harbor Times,Fuel Efficiency,None,NaN,5211,2038
38593,2367597833,Victor Harbor Times,A350,None,NaN,5211,2038
38594,2367597833,Victor Harbor Times,Cabin Technology,None,NaN,5211,2038
38595,2367597833,Victor Harbor Times,A330,None,NaN,5211,2038
38596,2367597833,Victor Harbor Times,Airbus:Cabin Technology,None,NaN,5211,2038
38597,2367597833,Victor Harbor Times,Boeing,None,NaN,5211,2038
38598,2367597833,Victor Harbor Times,Technology,None,NaN,5211,2038
38599,2367597833,Victor Harbor Times,A320,None,NaN,5211,2038
38600,2367597833,Victor Harbor Times,Airbus:Fuel Efficiency,None,NaN,5211,2038
38601,2367597833,Victor Harbor Times,Airbus,None,NaN,5211,2038
38602,2367597833,Victor Harbor Times,787,None,NaN,5211,2038
38603,2367597833,Victor Harbor Times,A380,None,NaN,5211,2038
38604,2367597833,Victor Harbor Times,Airbus:Technology,None,NaN,5211,2038
38605,2298705886,Sydney Morning Herald,Safety,None,NaN,NSW 2001,3461674
38606,2298705886,Sydney Morning Herald,Airbus,None,NaN,NSW 2001,3461674
38607,2298705886,Sydney Morning Herald,A321,None,NaN,NSW 2001,3461674
38608,2199743813,Binghamton Homepage,757,None,NaN,13903,18349
38609,2199743813,Binghamton Homepage,Boeing,None,NaN,13903,18349
38610,2380343416,@planet4589,Corporate,None,NaN,02143,23350
38611,2380343416,@planet4589,Airbus,None,NaN,02143,23350
38612,2380343416,@planet4589,Airbus:Corporate,None,NaN,02143,23350
38613,2355426359,The Guardian,A350 XWB,None,NaN,N19GU,225629
38614,2355426359,The Guardian,787-9,None,NaN,N19GU,225629
38615,2355426359,The Guardian,A350,None,NaN,N19GU,225629
38616,2355426359,The Guardian,Boeing,None,NaN,N19GU,225629
38617,2355426359,The Guardian,Airbus,None,NaN,N19GU,225629
38618,2355426359,The Guardian,A380,None,NaN,N19GU,225629
38619,2355426359,The Guardian,787,None,NaN,N19GU,225629

In [14]:
df.to_csv('airbus_bhqlite_excerpt.csv')

In [15]:
df = pd.read_csv('airbus_bhqlite_excerpt.csv')

In [16]:
df = df.drop('Unnamed: 0', axis=1)

In [17]:
df

,article_id,outlet_name,tag_name,provider,provider_value,zip_code,reach_circulation
0,2204316724,Air Transport World,Airbus:Aircraft Production,GnipTwitter,14.0,20910,154308
1,2204316724,Air Transport World,A350,GnipTwitter,14.0,20910,154308
2,2204316724,Air Transport World,Aircraft Production,GnipTwitter,14.0,20910,154308
3,2204316724,Air Transport World,Airbus,GnipTwitter,14.0,20910,154308
4,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,76865318
5,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,76865318
6,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,76865318
7,2203628156,New York Times,Airbus,Majestic,299.0,10018,76865318
8,2203628156,New York Times,Airbus,Majestic,299.0,10018,76865318
9,2203628156,New York Times,Airbus,Majestic,299.0,10018,76865318
10,2203628156,New York Times,Boeing,Majestic,299.0,10018,76865318
11,2203628156,New York Times,Boeing,Majestic,299.0,10018,76865318
12,2203628156,New York Times,Boeing,Majestic,299.0,10018,76865318
13,2203377430,CNN,737,GnipTwitter,7.0,30303,76918430
14,2203377430,CNN,A350,GnipTwitter,7.0,30303,76918430
15,2203377430,CNN,Airbus,GnipTwitter,7.0,30303,76918430
16,2203377430,CNN,A330,GnipTwitter,7.0,30303,76918430
17,2203377430,CNN,Asia-Pacific,GnipTwitter,7.0,30303,76918430
18,2203377430,CNN,Boeing,GnipTwitter,7.0,30303,76918430
19,2203377430,CNN,A321NEO,GnipTwitter,7.0,30303,76918430
20,2203377430,CNN,787,GnipTwitter,7.0,30303,76918430
21,2203377430,CNN,777,GnipTwitter,7.0,30303,76918430
22,2203401776,CNN Money,737,GnipTwitter,7.0,10019,11800000
23,2203401776,CNN Money,A350,GnipTwitter,7.0,10019,11800000
24,2203401776,CNN Money,Airbus,GnipTwitter,7.0,10019,11800000
25,2203401776,CNN Money,A330,GnipTwitter,7.0,10019,11800000
26,2203401776,CNN Money,Asia-Pacific,GnipTwitter,7.0,10019,11800000
27,2203401776,CNN Money,Boeing,GnipTwitter,7.0,10019,11800000
28,2203401776,CNN Money,A321NEO,GnipTwitter,7.0,10019,11800000
29,2203401776,CNN Money,787,GnipTwitter,7.0,10019,11800000
...,...,...,...,...,...,...,...
38590,2201899183,@NewYorkCP,Airbus,NaN,NaN,13425,6446
38591,2201899183,@NewYorkCP,A321,NaN,NaN,13425,6446
38592,2367597833,Victor Harbor Times,Fuel Efficiency,NaN,NaN,5211,2038
38593,2367597833,Victor Harbor Times,A350,NaN,NaN,5211,2038
38594,2367597833,Victor Harbor Times,Cabin Technology,NaN,NaN,5211,2038
38595,2367597833,Victor Harbor Times,A330,NaN,NaN,5211,2038
38596,2367597833,Victor Harbor Times,Airbus:Cabin Technology,NaN,NaN,5211,2038
38597,2367597833,Victor Harbor Times,Boeing,NaN,NaN,5211,2038
38598,2367597833,Victor Harbor Times,Technology,NaN,NaN,5211,2038
38599,2367597833,Victor Harbor Times,A320,NaN,NaN,5211,2038
38600,2367597833,Victor Harbor Times,Airbus:Fuel Efficiency,NaN,NaN,5211,2038
38601,2367597833,Victor Harbor Times,Airbus,NaN,NaN,5211,2038
38602,2367597833,Victor Harbor Times,787,NaN,NaN,5211,2038
38603,2367597833,Victor Harbor Times,A380,NaN,NaN,5211,2038
38604,2367597833,Victor Harbor Times,Airbus:Technology,NaN,NaN,5211,2038
38605,2298705886,Sydney Morning Herald,Safety,NaN,NaN,NSW 2001,3461674
38606,2298705886,Sydney Morning Herald,Airbus,NaN,NaN,NSW 2001,3461674
38607,2298705886,Sydney Morning Herald,A321,NaN,NaN,NSW 2001,3461674
38608,2199743813,Binghamton Homepage,757,NaN,NaN,13903,18349
38609,2199743813,Binghamton Homepage,Boeing,NaN,NaN,13903,18349
38610,2380343416,@planet4589,Corporate,NaN,NaN,02143,23350
38611,2380343416,@planet4589,Airbus,NaN,NaN,02143,23350
38612,2380343416,@planet4589,Airbus:Corporate,NaN,NaN,02143,23350
38613,2355426359,The Guardian,A350 XWB,NaN,NaN,N19GU,225629
38614,2355426359,The Guardian,787-9,NaN,NaN,N19GU,225629
38615,2355426359,The Guardian,A350,NaN,NaN,N19GU,225629
38616,2355426359,The Guardian,Boeing,NaN,NaN,N19GU,225629
38617,2355426359,The Guardian,Airbus,NaN,NaN,N19GU,225629
38618,2355426359,The Guardian,A380,NaN,NaN,N19GU,225629
38619,2355426359,The Guardian,787,NaN,NaN,N19GU,225629

In [46]:
df['parent_tag'] = df['tag_name'].str.split(':').str.get(0)

In [47]:
df['child_tag'] = df['tag_name'].str.split(':').str.get(1)

In [48]:
df

,article_id,outlet_name,tag_name,provider,provider_value,zip_code,parent_tag,child_tag
0,2204316724,Air Transport World,Airbus:Aircraft Production,GnipTwitter,14.0,20910,Airbus,Aircraft Production
1,2204316724,Air Transport World,A350,GnipTwitter,14.0,20910,A350,NaN
2,2204316724,Air Transport World,Aircraft Production,GnipTwitter,14.0,20910,Aircraft Production,NaN
3,2204316724,Air Transport World,Airbus,GnipTwitter,14.0,20910,Airbus,NaN
4,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,Fuel Efficiency,NaN
5,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,Fuel Efficiency,NaN
6,2203628156,New York Times,Fuel Efficiency,Majestic,299.0,10018,Fuel Efficiency,NaN
7,2203628156,New York Times,Airbus,Majestic,299.0,10018,Airbus,NaN
8,2203628156,New York Times,Airbus,Majestic,299.0,10018,Airbus,NaN
9,2203628156,New York Times,Airbus,Majestic,299.0,10018,Airbus,NaN
10,2203628156,New York Times,Boeing,Majestic,299.0,10018,Boeing,NaN
11,2203628156,New York Times,Boeing,Majestic,299.0,10018,Boeing,NaN
12,2203628156,New York Times,Boeing,Majestic,299.0,10018,Boeing,NaN
13,2203377430,CNN,737,GnipTwitter,7.0,30303,737,NaN
14,2203377430,CNN,A350,GnipTwitter,7.0,30303,A350,NaN
15,2203377430,CNN,Airbus,GnipTwitter,7.0,30303,Airbus,NaN
16,2203377430,CNN,A330,GnipTwitter,7.0,30303,A330,NaN
17,2203377430,CNN,Asia-Pacific,GnipTwitter,7.0,30303,Asia-Pacific,NaN
18,2203377430,CNN,Boeing,GnipTwitter,7.0,30303,Boeing,NaN
19,2203377430,CNN,A321NEO,GnipTwitter,7.0,30303,A321NEO,NaN
20,2203377430,CNN,787,GnipTwitter,7.0,30303,787,NaN
21,2203377430,CNN,777,GnipTwitter,7.0,30303,777,NaN
22,2203401776,CNN Money,737,GnipTwitter,7.0,10019,737,NaN
23,2203401776,CNN Money,A350,GnipTwitter,7.0,10019,A350,NaN
24,2203401776,CNN Money,Airbus,GnipTwitter,7.0,10019,Airbus,NaN
25,2203401776,CNN Money,A330,GnipTwitter,7.0,10019,A330,NaN
26,2203401776,CNN Money,Asia-Pacific,GnipTwitter,7.0,10019,Asia-Pacific,NaN
27,2203401776,CNN Money,Boeing,GnipTwitter,7.0,10019,Boeing,NaN
28,2203401776,CNN Money,A321NEO,GnipTwitter,7.0,10019,A321NEO,NaN
29,2203401776,CNN Money,787,GnipTwitter,7.0,10019,787,NaN
...,...,...,...,...,...,...,...,...
38590,2201899183,@NewYorkCP,Airbus,None,NaN,13425,Airbus,NaN
38591,2201899183,@NewYorkCP,A321,None,NaN,13425,A321,NaN
38592,2367597833,Victor Harbor Times,Fuel Efficiency,None,NaN,5211,Fuel Efficiency,NaN
38593,2367597833,Victor Harbor Times,A350,None,NaN,5211,A350,NaN
38594,2367597833,Victor Harbor Times,Cabin Technology,None,NaN,5211,Cabin Technology,NaN
38595,2367597833,Victor Harbor Times,A330,None,NaN,5211,A330,NaN
38596,2367597833,Victor Harbor Times,Airbus:Cabin Technology,None,NaN,5211,Airbus,Cabin Technology
38597,2367597833,Victor Harbor Times,Boeing,None,NaN,5211,Boeing,NaN
38598,2367597833,Victor Harbor Times,Technology,None,NaN,5211,Technology,NaN
38599,2367597833,Victor Harbor Times,A320,None,NaN,5211,A320,NaN
38600,2367597833,Victor Harbor Times,Airbus:Fuel Efficiency,None,NaN,5211,Airbus,Fuel Efficiency
38601,2367597833,Victor Harbor Times,Airbus,None,NaN,5211,Airbus,NaN
38602,2367597833,Victor Harbor Times,787,None,NaN,5211,787,NaN
38603,2367597833,Victor Harbor Times,A380,None,NaN,5211,A380,NaN
38604,2367597833,Victor Harbor Times,Airbus:Technology,None,NaN,5211,Airbus,Technology
38605,2298705886,Sydney Morning Herald,Safety,None,NaN,NSW 2001,Safety,NaN
38606,2298705886,Sydney Morning Herald,Airbus,None,NaN,NSW 2001,Airbus,NaN
38607,2298705886,Sydney Morning Herald,A321,None,NaN,NSW 2001,A321,NaN
38608,2199743813,Binghamton Homepage,757,None,NaN,13903,757,NaN
38609,2199743813,Binghamton Homepage,Boeing,None,NaN,13903,Boeing,NaN
38610,2380343416,@planet4589,Corporate,None,NaN,02143,Corporate,NaN
38611,2380343416,@planet4589,Airbus,None,NaN,02143,Airbus,NaN
38612,2380343416,@planet4589,Airbus:Corporate,None,NaN,02143,Airbus,Corporate
38613,2355426359,The Guardian,A350 XWB,None,NaN,N19GU,A350 XWB,NaN
38614,2355426359,The Guardian,787-9,None,NaN,N19GU,787-9,NaN
38615,2355426359,The Guardian,A350,None,NaN,N19GU,A350,NaN
38616,2355426359,The Guardian,Boeing,None,NaN,N19GU,Boeing,NaN
38617,2355426359,The Guardian,Airbus,None,NaN,N19GU,Airbus,NaN
38618,2355426359,The Guardian,A380,None,NaN,N19GU,A380,NaN
38619,2355426359,The Guardian,787,None,NaN,N19GU,787,NaN

In [49]:
indexNames = df[(df['provider'] == 'Majestic') | (df['provider'] == 'GnipTwitter:Retro') | (df['provider'] == 'LinkedIn') | (df['provider'] == 'Facebook:comments')].index
df.drop(indexNames, inplace=True)

In [50]:
df['provider'].value_counts()

GnipTwitter        6356
Facebook:shares    3143
Name: provider, dtype: int64

In [51]:
df['child_tag'].value_counts()

Financial Perf.         989
Aircraft Production     836
Sales                   765
Corporate               439
Airbus                  438
Boeing                  333
Fuel Efficiency         323
Technology              319
Spokesperson            249
Cabin Technology        221
Government Relations    166
Asia-Pacific            143
Share Value             124
Earnings                103
CEO                      98
Influencer Feedback      88
Middle East              76
Labor Relations          66
Bombardier               63
M&A                      51
Safety                   48
Legislation              41
United States            38
North America            30
Eurozone                 30
United Kingdom           25
EU ETS                   19
Passenger Safety         19
Emerging Technology      17
Employee                 14
FAA                      12
Tech Safety               8
CSR                       4
Fuel Prices               3
Winglets/Sharklets        3
Litigation                2
Customer Service          2
India                     1
Financial Analyst         1
Noise Reduction           1
Latin America             1
Name: child_tag, dtype: int64

In [52]:
parent_tag_list = ['Airbus', 'Boeing']
child_tag_list = ['Aircraft Production', 'Corporate', 'Financial Perf.', 'Safety', 'Government Relations', 'Technology']

In [18]:
df_filtered = df[df['tag_name'] == 'Airbus:Corporate']

In [19]:
df_filtered

,article_id,outlet_name,tag_name,provider,provider_value,zip_code,reach_circulation
3389,2247525465,iTnews Australia,Airbus:Corporate,GnipTwitter,6.0,2016,101941
5223,2395661284,South China Morning Post,Airbus:Corporate,GnipTwitter,43.0,00000,3863588
5243,2395661284,South China Morning Post,Airbus:Corporate,Facebook:shares,11.0,00000,3863588
5263,2395661284,South China Morning Post,Airbus:Corporate,LinkedIn,1.0,00000,3863588
5559,2396806814,Hindu Business Line,Airbus:Corporate,Facebook:shares,1.0,600002,1488347
5574,2396806814,Hindu Business Line,Airbus:Corporate,LinkedIn,1.0,600002,1488347
5589,2397607971,Aviation India,Airbus:Corporate,Majestic,3.0,NaN,1936
6032,2321454507,Bloomberg,Airbus:Corporate,GnipTwitter,10.0,10022,21980000
6137,2322211302,Wall Street Journal,Airbus:Corporate,LinkedIn,1.0,10281,44778827
6138,2322211302,Wall Street Journal,Airbus:Corporate,LinkedIn,1.0,10281,44778827
6139,2322211302,Wall Street Journal,Airbus:Corporate,LinkedIn,1.0,10281,44778827
6158,2322211302,Wall Street Journal,Airbus:Corporate,Facebook:shares,2.0,10281,44778827
6159,2322211302,Wall Street Journal,Airbus:Corporate,Facebook:shares,2.0,10281,44778827
6160,2322211302,Wall Street Journal,Airbus:Corporate,Facebook:shares,2.0,10281,44778827
6179,2322211302,Wall Street Journal,Airbus:Corporate,GnipTwitter,4.0,10281,44778827
6180,2322211302,Wall Street Journal,Airbus:Corporate,GnipTwitter,4.0,10281,44778827
6181,2322211302,Wall Street Journal,Airbus:Corporate,GnipTwitter,4.0,10281,44778827
6188,2322210797,4 Traders,Airbus:Corporate,LinkedIn,2.0,74000,1019
7259,2334390647,Sky News,Airbus:Corporate,GnipTwitter:Retro,337.0,TW7 5QD,3802423
7264,2334390647,Sky News,Airbus:Corporate,GnipTwitter,338.0,TW7 5QD,3802423
7269,2334589240,Yahoo! Finance UK,Airbus:Corporate,GnipTwitter:Retro,2.0,WC2H 8AD,4000000
7274,2334589240,Yahoo! Finance UK,Airbus:Corporate,GnipTwitter,2.0,WC2H 8AD,4000000
7282,2334318680,The Telegraph (UK),Airbus:Corporate,GnipTwitter,1.0,ME4 4TT,9846804
7291,2334233940,Bloomberg,Airbus:Corporate,GnipTwitter,5.0,10022,21980000
7577,2335164149,New York Times,Airbus:Corporate,GnipTwitter,2.0,10018,76865318
7578,2335164149,New York Times,Airbus:Corporate,GnipTwitter,2.0,10018,76865318
7579,2335164149,New York Times,Airbus:Corporate,GnipTwitter,2.0,10018,76865318
7900,2343770147,The Telegraph (UK),Airbus:Corporate,GnipTwitter,2.0,ME4 4TT,9846804
8301,2350134776,Economic Times,Airbus:Corporate,GnipTwitter:Retro,12.0,110002,4220000
8313,2350134776,Economic Times,Airbus:Corporate,GnipTwitter,12.0,110002,4220000
...,...,...,...,...,...,...,...
34050,2359567530,Metro.us,Airbus:Corporate,NaN,NaN,19102,183494
35008,2350122198,Channel NewsAsia,Airbus:Corporate,NaN,NaN,299939,1396600
35061,2350109961,Reuters UK,Airbus:Corporate,NaN,NaN,E14 5EP,36716994
35360,2335193742,The Telegraph (UK),Airbus:Corporate,NaN,NaN,ME4 4TT,9846804
35394,2398860932,@nicx62,Airbus:Corporate,NaN,NaN,NaN,6477
35736,2334392019,Heart Radio,Airbus:Corporate,NaN,NaN,00000,163106
36239,2370964167,International Business Times India,Airbus:Corporate,NaN,NaN,560008,723785
36299,2392575805,Agence France-Presse,Airbus:Corporate,NaN,NaN,75002,484222
36310,2350103171,Sharenet,Airbus:Corporate,NaN,NaN,7966,47912
36375,2334432767,SamFM.co.uk,Airbus:Corporate,NaN,NaN,BS3 2JH,5097
36544,2350109960,Yahoo! Finance UK,Airbus:Corporate,NaN,NaN,WC2H 8AD,4000000
36705,2326881312,@R_Wall,Airbus:Corporate,NaN,NaN,NaN,10912
36752,2414066226,Force India,Airbus:Corporate,NaN,NaN,NaN,4485
36882,2397633136,@5amStartups,Airbus:Corporate,NaN,NaN,NaN,7902
36914,2359564872,Yahoo! Finance,Airbus:Corporate,NaN,NaN,00000,75000000
36925,2379321267,Yahoo! India,Airbus:Corporate,NaN,NaN,00000,28500000
36998,2379316457,Yahoo! News Singapore,Airbus:Corporate,NaN,NaN,NaN,3400000
37465,2359660533,Yahoo! News Singapore,Airbus:Corporate,NaN,NaN,NaN,3400000
37574,2350108418,92.9 WLMI,Airbus:Corporate,NaN,NaN,48842,713
37670,2379321266,Philadelphia Inquirer,Airbus:Corporate,NaN,NaN,19101,474015
37671,2379321266,Philadelphia Inquirer,Airbus:Corporate,NaN,NaN,19101,474015
37672,2379321266,Philadelphia Inquirer,Airbus:Corporate,NaN,NaN,19101,474015
37789,2359665783,Edge Markets,Airbus:Corporate,NaN,NaN,00000,190630
37929,2359564450,WTAQ News Talk,Airbus:Corporate,NaN,NaN,54305,3975
38104,2334440170,Metro Radio,Airbus:Corporate,NaN,NaN,NE1 6BL,101
38146,2334392912,Lakeland Radio,Airbus:Corporate,NaN,NaN,LA8 8QJ,1325
38274,2350174182,Metro.us,Airbus:Corporate,NaN,NaN,19102,183494
38456,2334399270,Radio City Talk,Airbus:Corporate,NaN,NaN,L1 1RL,1631
38461,2379310198,Sharenet,Airbus:Corporate,NaN,NaN,7966,47912
38612,2380343416,@planet4589,Airbus:Corporate,NaN,NaN,02143,23350

In [27]:
df_outlet_volume = df.groupby('outlet_name')[['article_id']].nunique().reset_index()

In [28]:
df_outlet_sharing = df.groupby(['outlet_name', 'article_id', 'provider'])[['provider_value']].min().reset_index()

In [29]:
df_outlet_sharing_totals = df_outlet_sharing.groupby('outlet_name')[['provider_value']].sum().reset_index()

In [72]:
df_outlet_sharing_totals

                                    outlet_name  provider_value
0                                      11 Alive             1.0
1                                   3DPrint.com           137.0
2                                     4 Traders             1.0
3                                      680 News             3.0
4                                      ABC News           157.0
5                                       AIRwise             1.0
6                                      AME Info            18.0
7                               AVIATIONNEWS.EU             2.0
8                              Accounting Today            19.0
9                             Ace News Services             1.0
10                         Aerospace Technology            32.0
11                 Aerospace Technology-Updates            28.0
12                         Agence France-Presse           516.0
13                      Agence Kampuchea Presse            11.0
14                              Air Cargo World             7.0
15                          Air Transport World           411.0
16                                     Airchive            15.0
17                                 Airways News            15.0
18                                     Al Ahram             5.0
19                                   Al Jazeera            63.0
20                           Albury Border Mail             5.0
21                                   All Africa            27.0
22                                       Aloria           917.0
23   American Journal of Transportation On-Line             8.0
24                           American Machinist             2.0
25                                     An Nahar             1.0
26                         Anchorage Daily News           108.0
27                                    Anna.aero            15.0
28                                    Arab News             1.0
29                            Arabian Aerospace            12.0
..                                          ...             ...
328                                WBAL Channel            14.0
329                                  WBOC TV 16             1.0
330                                        WHBL             1.0
331                                        WHTC             1.0
332                                        WKRG          1198.0
333                                        WLTX             1.0
334                                        WRAL             1.0
335                                        WTHR             3.0
336                                Wales Online             1.0
337                         Wall Street Journal          7113.0
338                             Washington Post           609.0
339                            Wauchope Gazette             1.0
340                             West Australian             6.0
341                    Wichita Business Journal             1.0
342                               Wichita Eagle           238.0
343                          Xinhua News Agency            87.0
344                              Yahoo! Finance            73.0
345                           Yahoo! Finance UK            55.0
346                                Yahoo! India            34.0
347                                 Yahoo! News           228.0
348                       Yahoo! News Australia             3.0
349                          Yahoo! News Canada             3.0
350                       Yahoo! News Singapore             1.0
351                          Yeshiva World News             4.0
352                Young Travelers of Hong Kong             2.0
353                                       ZDNet           187.0
354                              bivnze's space             3.0
355                             defencetalk.com             1.0
356                                    gCaptain           102.0
357                            iTnews Australia             7.0

[358 rows x 2 columns]

In [24]:
df_outlet_reach = df_filtered.groupby('outlet_name')[['reach_circulation']].min().reset_index()

In [25]:
df_outlet_reach

                     outlet_name  reach_circulation
0                            3FM              10194
1                      4 Traders               1019
2                      92.9 WLMI                713
3               96.4 Eagle Radio                101
4                   @5amStartups               7902
5                   @ACScowcroft               9871
6                   @APM_Powders                 63
7                       @CarinaH                690
8                       @GescheW               1611
9                        @R_Wall              10912
10                @_MrDavidJones               5425
11                  @andytoronto               5877
12                  @jetcitystar              14925
13                       @nicx62               6477
14                        @pbdes               9421
15                   @planet4589              23350
16                    @roomeezon              12615
17                @singh_baldev5               5584
18                     @spacecom              13786
19                   ADVFN India             959270
20          Agence France-Presse             484222
21            American Machinist              15291
22                     Arab News             638154
23              Asia Travel Tips               2344
24              Associated Press             943979
25                Aviation India               1936
26   Aviation International News              85630
27                Aviation Today              21407
28              Big News Network              20388
29                     Bloomberg           21980000
..                           ...                ...
99                      Sharenet              47912
100                     Sky News            3802423
101           Sky News Australia              77475
102     South China Morning Post            3863588
103                  Stuff.co.nz            2150968
104          Tacoma News Tribune             185692
105                    The Beach                101
106             The Fiscal Times              23446
107               The Gulf Today              35679
108          The Malaysian Times               8359
109              The Rakyat Post              29563
110           The Telegraph (UK)            9846804
111                 Today Online             497475
112                  Town 102 FM                407
113                 Trade Arabia              34660
114              UAE NewsApp.com               1834
115                VIBE 107.6 FM                407
116                         WHBL               3466
117                         WHTC               7339
118                      WKZO-AM               8257
119                      WSAU-AM              16310
120               WTAQ News Talk               3975
121          Wall Street Journal           44778827
122               Yahoo! Finance           75000000
123            Yahoo! Finance UK            4000000
124                 Yahoo! India           28500000
125                  Yahoo! News           75000000
126           Yahoo! News Canada            1444000
127        Yahoo! News Singapore            3400000
128             iTnews Australia             101941

[129 rows x 2 columns]

In [32]:
df_outlet_merged = pd.merge(df_outlet_volume, df_outlet_sharing_totals, how='left', on='outlet_name')

In [33]:
df_outlet_merged = df_outlet_merged.fillna(0)

In [34]:
df_outlet_merged = pd.merge(df_outlet_merged, df_outlet_reach, how='left', on='outlet_name')

In [36]:
df_outlet_merged.fillna(0)

,outlet_name,article_id,provider_value,reach_circulation
0,#GCC and #MiddleEast Finance News,1,0.0,0.0
1,100 WAPI,1,0.0,0.0
2,1057 EZRrock,1,0.0,0.0
3,11 Alive,1,1.0,0.0
4,12 News Now,1,0.0,0.0
5,14 WFIE,2,0.0,0.0
6,1440 WNFL,11,0.0,0.0
7,1490Wosh.com,1,0.0,0.0
8,16 WAPT,2,0.0,0.0
9,19 Action News,1,0.0,0.0
10,3 WRCB-TV,1,0.0,0.0
11,35 WSEE,1,0.0,0.0
12,3DPrint.com,1,311.0,0.0
13,3FM,1,0.0,10194.0
14,3novicesafrican,2,0.0,0.0
15,3novicesasia,4,0.0,0.0
16,4 Traders,50,3.0,1019.0
17,4029 TV,2,1.0,0.0
18,41 NBC,1,0.0,0.0
19,570 News,2,0.0,0.0
20,580 CFRA,1,0.0,0.0
21,590 KLBJ,1,0.0,0.0
22,660 News,2,0.0,0.0
23,680 News,2,3.0,0.0
24,77 WABC RADIO,1,0.0,0.0
25,92.9 WLMI,32,0.0,713.0
26,94.5 KSMB,1,0.0,0.0
27,949 KCMO,1,0.0,0.0
28,96.4 Eagle Radio,1,0.0,101.0
29,997WTN.com,1,0.0,0.0
...,...,...,...,...
1546,XinMsn,2,0.0,0.0
1547,Xinhua News Agency,9,168.0,0.0
1548,YOUR BASIN,2,0.0,0.0
1549,Yahoo! Finance,66,384.0,75000000.0
1550,Yahoo! Finance UK,81,398.0,4000000.0
1551,Yahoo! India,33,39.0,28500000.0
1552,Yahoo! Maktoob News,10,0.0,0.0
1553,Yahoo! New Zealand News,9,0.0,0.0
1554,Yahoo! News,36,604.0,75000000.0
1555,Yahoo! News Australia,10,23.0,0.0
1556,Yahoo! News Canada,26,4.0,1444000.0
1557,Yahoo! News Singapore,39,1.0,3400000.0
1558,Yakima Herald,1,0.0,0.0
1559,Yass Tribune,4,0.0,0.0
1560,Yerepouni Daily News.,1,0.0,0.0
1561,Yeshiva World News,1,5.0,0.0
1562,Young Travelers of Hong Kong,1,3.0,0.0
1563,YourCentralValley.com,2,1.0,0.0
1564,ZDNet,1,277.0,0.0
1565,ZeeNews.com,2,0.0,0.0
1566,Zionsville Times Sentinel,1,0.0,0.0
1567,bivnze's space,1,3.0,0.0
1568,defencetalk.com,1,1.0,0.0
1569,gCaptain,1,175.0,0.0
1570,iTnews Australia,3,7.0,101941.0
1571,news and real estate,1,0.0,0.0
1572,rci-ventures,1,0.0,0.0
1573,satPRnews,5,3.0,0.0
1574,αακηρατος δελφων,1,0.0,0.0
1575,بلیط یاب - راهنمای خرید بلیط هواپیمابلیط یاب –...,10,3.0,0.0